### ISSUE TITLE
Doom Emacs installation and configuration

### ISSUE THREAD

**Issue by Martin-2025s** [gicrisf/tochemfig#1]
Dear Author!

How to configure Your package to work with doom emacs. I wrote recipe in package el. and (setq tochemfig-default-input 'direct') in config.el.

mol2chemfigpy3 is installed too...

The emacs does not see (?) this package?

Thank You in advance!

**Comment by gicrisf** [comment]
Hey, I'm not able to check the package issue now as it's late and I have work tomorrow. However, since all the code is stored in a single file, you can easily try an old-style workaround by cloning the repository, opening `tochemfig.el` in Emacs, and running `emacs-lisp-byte-compile-and-load` (just press Alt+x and write the command). This should make the interactive functions available. If you want to autoload it, you can add `(load! "/path/to/tochemfig/tochemfig.el")` in your config.el file. It's not the cleanest solution, but I hope this helps you work right away.

**Comment by Martin-2025s** [comment]
Thank You for your quick response.

The solutions suggested work, admittedly they are half measures, but they do work.

The original recipe with doom emacs - unfortunately not.

I will look for the error, deeper.

Thank You - a really good piece of programming work.

**Comment by gicrisf** [comment]
I'm glad to read you're enjoying my package! 

In the meantime, I found the issue. At first, I developed the package for my own use case, so I loaded all functions using Emacs' autoload magic comment. But then I realized it wasn't great since there are many functions you don't use in your daily activity. It would be better to load them in specific buffers, only when you work with molecules. So, I decided a minor mode for Emacs was the solution. However, I haven't created the minor mode function yet, so that part is currently broken. Considering your interest in the project, I'll try to finalize it. If I find I never have time to do it, I'll give you a working branch with the old style, even if it's a bit rough.

**Comment by Martin-2025s** [comment]
It will be some repair work in progress ...?

**Comment by gicrisf** [comment]
> It will be some repair work in progress ...?

Yes, I was working on that, but I had to pause everything because of some big changes in my private life, and I have no time to test it out right now. I hope in the meanwhile you can endure by loading the code from the config file

**Comment by Martin-2025s** [comment]
OK! Thank You, for Your efforts.

**Comment by gicrisf** [comment]
Hi! I have just committed a new version. I tested it tonight. It should load a tochemfig-mode interactive function only at startup. If you run it, it will load all the associated functions for you. This way, your environment will not be polluted by the many functions when you do not need them.

Doom Emacs installation:

```emacs-lisp
;; in ~/.doom.d/packages.el
(package! tochemfig
  :recipe (:host github :repo "gicrisf/tochemfig"))

;; in ~/.doom.d/config.el
(use-package! tochemfig)
```

**Comment by Martin-2025s** [comment]
Thank You, for your great work!

**Comment by gicrisf** [comment]
I'm glad it works well for you! Let me know if you have any ideas for further improvements. I cannot guarantee a quick response because I do this in my free time, but I will be glad to help if I can.
